volumes:
  nginx:
  ui:


services:
  nginx-ui:
    image: uozi/nginx-ui:latest
    environment:
      - TZ=Asia/Shanghai
      - NGINX_UI_SERVER_PORT=8080
      - NGINX_UI_IGNORE_DOCKER_SOCKET=true
      - NGINX_UI_LOGROTATE_ENABLED=true
    volumes:
      - nginx:/etc/nginx
      - ui:/etc/nginx-ui
    ports:
      - "8080:8080"
      - "90:90"
      - "9000-9090:9000-9090"
